---
version: 2
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: "deps"
    directory: /
    labels:
      - automated
      - dependencies
      - github-actions
    schedule:
      interval: weekly
...
