---
name: Update Dependencies

on:
  schedule:
    - cron: '0 22 * * FRI'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-flake:
    name: Update Nix flake dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "deps: update Nix flake dependencies"
          pr-labels: |
            automated
            dependencies
            nix
          token: ${{ secrets.UPDATE_DEPENDENCIES_TOKEN }}
...
